import { Raffle } from "./raffle.ts";
import { Price } from "./price.ts";

const candidates = [
  "@Gangsta2007",
  "@LockeDerBoss",
  "@MiiMiiSeinBruder",
  "@AlphaKevin",
  "@RedSoldier499",
  "@Louisa12",
  "@Drachenlord",
  "@Tanzverbot",
  "@tiger10ab",
  "@kaesekrokette99",
  "@fortnite4ever",
  "@ColdplayFan",
  "@Sören2013",
  "@MichiJackson",
  "@WBSLegal",
  "@Ronaldo7",
  "@Timmmäääh",
  "@SonGoku2011",
  "@NarutoBoy2000",
  "@Diggah69",
  "@roflomat",
  "@waifu_weeb",
  "@derp",
  "@MaxPower9000",
  "@MikrowellenPizza2006",
  "@MeddlFan",
  "@SpecialNeedChild37",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@LeonMachere",
  "@SimonDesue",
  "@SimonDesue",
  "@SimonDesue",
  "@SimonDesue",
  "@SimonDesue",
  "@SimonDesue",
  "@PrinzPuma",
  "@PrinzPuma",
  "@PrinzPuma",
  "@PrinzPuma",
];
const prices = [
  new Price("iPhone 17 Pro", 1),
  new Price("Trip nach Dubi", 1),
  new Price("Stepper nach Isti", 1),
  new Price("Flug nach Zypi", 1),
  new Price("10 kg Haribo", 2),
  new Price("PlayStation 5 Slim", 3),
  new Price("gebrauchte Sneaker", 5),
];
const winners = new Raffle(candidates, prices).run();
for (const [winner, price] of winners.entries()) {
  console.log(`${winner} gewinnt ${price}`);
}
